## Pratice

In [17]:
import numpy as np

a= np.ones(3)
a

array([1., 1., 1.])

In [5]:
a1= np.empty(5)
a1

array([1.35505944e+248, 3.01468742e+161, 2.44046037e-152, 8.71073381e+183,
       1.64039829e-118])

In [8]:
a2=np.ones([3,2])
a2

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
a3=np.full(5,2)
a3

array([2, 2, 2, 2, 2])

In [15]:
a4= np.random.random([3,4])
a4

array([[0.21034994, 0.96951857, 0.3976469 , 0.21878694],
       [0.82703653, 0.49562228, 0.68893967, 0.07105976],
       [0.61423427, 0.17139258, 0.67868927, 0.56400393]])

In [20]:
a.shape

(3,)

In [13]:
arr= [6,7,8,9]

ar= np.array(arr)

print(type(ar))

<class 'numpy.ndarray'>


In [30]:
print(b.ndim)

2


In [29]:
b= np.zeros((5,5))
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
np.random.random((5,2))

array([[0.45439912, 0.93525849],
       [0.0680068 , 0.39426247],
       [0.37530608, 0.42100592],
       [0.91064691, 0.2621336 ],
       [0.76076312, 0.33521483]])

In [36]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
e=[[10,11,12],
  [13,14,15],
  [15,16,17],
  [18,19,20]]

e

[[10, 11, 12], [13, 14, 15], [15, 16, 17], [18, 19, 20]]

In [42]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])